config/routes.rb
Rails.application.routes.draw do
  #get 'pages/busqueda'
  #get 'busqueda', controller: :pages, action: :busqueda, alias: 'busqueda'
  #get 'registrate', controller: :pages, action: :registrate, alias: 'registrate'
  resources :users
  resources :parkings
  resources :home
  #resources :searches
=begin
    get "/users" index
    post "/users" create
    delete "/users" delete
    get "/users/:id" show
    get "/users/new" new
    get "/users/:id/edit" edit
    patch "users/:id" update
    put "users/:id" update
=end

  get :search, controller: :home

 
  #post 'user' => "pages#create" #Se envia los datos por post desde la vista registrate.html.erb
  get 'registro'   => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'actualizar' => 'pages#actualizar'

  root 'home#index'
  #get 'mis-estacionamiento', controller: :pages, action: :misestacionamiento, alias: 'mis-estacionamiento'
  #get 'reservacion', controller: :pages, action: :reservacion, alias: 'reservacion'
  #get 'cuenta', controller: :pages, action: :cuenta, alias: 'cuenta'
  get 'mis-reservaciones', controller: :pages, action: :misreservaciones, alias: 'mis-reservaciones'
  #get 'crear-estacionamiento', controller: :pages, action: :crearestacionamiento, alias: 'crear-estacionamiento'
  get 'ticket', controller: :pages, action: :ticket, alias: 'ticket'
  get 'actualizar', controller: :pages, action: :actualizar, alias: 'actualizar'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/parking.rb
class Parking < ApplicationRecord
    def self.search(params)
        parking = Parking.where("district LIKE ?", "%#{params}%") if params.present?
        parking #returns the parking
    end
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  http_basic_authenticate_with name: "mlagos@gmail.com", password: "123456", except: [:index, :show, :search]
  def index
  end
  def search
    search = params[:home][:search]
    logger.debug "Búsqueda: #{search}"
    if params[:home][:search].blank?
        @parkings = Parking.all
    else
        @parkings = Parking.search(search)
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def busqueda
  end

  def registrate
  end

  def sesion
  end

  def misestacionamiento
  end

  def reservacion
  end

  def cuenta
  end

  def misreservaciones
  end

  def crearestacionamiento
  end

  def ticket
  end

  def actualizar
  end
  
  def create
  end
end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController
    def index      
    end 
    def new
    end
    def show
        @parking = Parking.find(params[:id])
    end
    def create
        @parking = Parking.new(
            name: params[:parkings][:name],
            address: params[:parkings][:address],
            district: params[:parkings][:district],
            google_maps: params[:parkings][:google_maps],
            phone: params[:parkings][:phone],
            price: params[:parkings][:price],
            pkg_location: params[:parkings][:pkg_location],
            pkg_place: params[:parkings][:pkg_place],
            quantity: params[:parkings][:quantity],
            service_wash: params[:parkings][:service_wash],
            service_rest: params[:parkings][:service_rest],
            service_atm: params[:parkings][:service_atm],
            service_24_7: params[:parkings][:service_24_7],
            camare_security: params[:parkings][:camare_security]
            )
        @parking.save
    end

    def search
        if params[:home][:search].blank?
            @parkings = Parking.all
        else
            @parkings = Parking.search(params)
        end
    end
  
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

    def index
        @parkings = Parking.all
    end
    def show
        @parkin = Parking.find(params[:district])
    end
  
    def search
        search = params[:searches][:search]
        logger.debug "Búsqueda: #{search}"
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    include SessionsHelper
    def new

    end
  
    def create
        puts "CREAR SESSION"
        user = User.find_by(email: params[:session][:email].downcase, password: params[:session][:password])
        
        if user
            puts "ENTRO!"
            log_in user
            redirect_to :users
        else
            flash[:danger] = 'Usuario y/o contraseña no son correctos'
            redirect_to :root
        end
    end
  
    def destroy
        log_out if logged_in?
        redirect_to :root
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index      
    end    
    def new
        @user = User.new
    end
    def create
        @user = User.new(
            first_name: params[:users][:first_name],
            last_name: params[:users][:last_name],
            type_document: params[:users][:type_document],
            n_document: params[:users][:n_document],
            f_birth: params[:users][:f_birth],
            phone: params[:users][:phone],
            sex: params[:users][:sex],
            email: params[:users][:email],
            password: params[:users][:password],
            remember_token: params[:users][:remember_token],
            tyc: params[:users][:tyc]
            )
        if @user.save
            redirect_to @home
        else
            render :new
        end
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
        session[:user_email] = user.email
    end
    
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        !current_user.nil?
    end
    
    def log_out
        session.delete(:user_id)
        session.delete(:user_email)
        @current_user = nil
    end
end

app/views/home/index.html.erb
<%-# Content Search -%>
<div class="content-head">
    <div class="info-head">
    <div class="txt-small">¿Buscas un <span class="color-amarillo">estacionamiento?</span></div>
    <div class="txt-two"><span class="color-amarillo">aquí</span> encontrarás tu estacionamiento en 3 simples pasos y no pierdas tiempo dando vueltas.</div>
    <%= form_for :home, method: :get, :url => { :action => :search } do |s| %>
        <div class="form-search cf">
        <div class="search_input">
            <i class="fa fa-map-marker"></i>
             <%= s.text_field :search, class: 'form-control', placeholder: 'Ej: Chorrillos' %>
        </div>
        <%= button_tag(type: "submit", id: "send", class: "a") do %>
            Buscar <i class="fa fa-long-arrow-right"></i>
        <% end %>
        <div id="btn-filter" class="btn-filter">Filtrar <i class="fa fa-filter"></i></div>
        </div>
    <% end %>
    </div>
    <div class="slider-background">
    <div class="list-slider" style="background-image: url(<%= asset_path 'background1.jpg' %>) ;"></div>
    </div>
    <div class="cloud-cluster">
    <div class="background">
        <div class="before"></div>
        <div class="after"></div>
    </div>
    <div class="foreground">
        <div class="before"></div>
        <div class="after"></div>
    </div>
    </div>
</div>  

<div class="wrapper-info">
    <div class="wrapper-content">
    <div class="title_principal align-center">Pasos para buscar tu estacionamiento</div>
    <p class="align-center subtitle_h3">Encuentra un lugar cerca de ti al mejor precio para estacionar unas horas o  varios días</p>
    <div class="row">
        <div class="col-sm-4 block-steep">
        <span class="number">1</span>
        <div class="step-image">
            <%= render 'step1' %>
        </div>
        <p>Busca la dirección donde deseas estacionarte</p>
        </div>
        <div class="col-sm-4 block-steep">
        <span class="number">2</span>
        <div class="step-image">
            <%= render 'step2' %>
        </div>
        <p>Puedes filtrar tu búsqueda. Además, seleccionar la hora de ingreso y salida.</p>
        </div>
        <div class="col-sm-4 block-steep">
        <span class="number">3</span>
        <div class="step-image">
            <%= render 'step3' %>
        </div>       
        <p>Compara precio y elige el estacionamiento más apropiado para ti</p>
        </div>
    </div>
    </div>      
</div>

<div class="wrapper-info-black">
    <div class="wrapper-content">
    <div class="title_principal align-center">¿Tienes el garaje vacío? Nosotros nos encargamos de que se alquile</div>
    <div class="cf">
        <div class="col-sm-8">            
        <p>Para poder ganar un dinero extra el tiempo que tu garaje está vacío no necesitas poner anuncios en decenas de páginas de clasificados. Ni prestar el mando o la llave para que entren al garaje. </p>
        <p>Alquilando tu plaza de tu estacionamiento con Aquí.pe, nosotros nos encargamos de todo. Tú sólo tendrás que preocuparte de en qué vas a gastar esos ingresos extra.</p>
      
            <%= link_to registro_path, :class => 'btn-yellow margin-bottom', :action => 'go' do %>
                Regístrate <i class="fa fa-long-arrow-right"></i>
            <% end %>
        </div>
        <div class="col-sm-4">
        <div class="img-parking">
            <%= render 'img-parking' %>
        </div>
        </div>
    </div>
    </div>      
</div>

app/views/home/search.html.erb
<div class="wrapper-search-inner wrapper-black">
    <div class="wrapper-content">
        <h1 class="title_principal align-center">Búsqueda de <span class="color-amarillo">estacionamiento</span></h1>
        <%= form_for :home, method: :get, :url => { :action => :search }, :html => {:class => 'form-search-inner', 'data-bar' => 'baz'} do |s| %>
            <div class="cf">
                <div class="col-sm-10">
                    <div class="label-s">
                        <%= s.label :search, '¿Dónde deseas estacionarte?:' %>
                    </div>
                    <div class="input-s">
                        <%= s.text_field :search, :value => 'Chorrillos' %>
                    </div>                    
                </div>
                <div class="col-sm-2">
                <%= button_tag(type: "submit", id: "send", class: "a btn_inner-search") do %>
                    Buscar <i class="fa fa-long-arrow-right"></i>
                <% end %>
                </div>
            </div>            
        <% end %>
    </div>
</div>
<div class="wrapper-result-e wrapper-gray">
    <div class="wrapper-content">
        <div class="result-parking">
            <div class="scroll-result cf">
                <% @parkings.each do |parkinge| %>
                <%= link_to parking_path(parkinge.id), class: "block-result cf" do %>
                    <div class="image">
                        <%= image_tag "img1.jpg", html: { alt: "image 1" } %>
                    </div>
                    <div class="description">
                        <div class="price"> S/ <%= parkinge.price%>.00 <span>PEN</span></div>
                        <div class="title"><%= parkinge.name %></div>
                        <div class="address"><%= parkinge.address %> - <%= parkinge.district %></div>
                        <div class="service">
                            <div class="icon-service"></div>
                            <div class="icon-service"></div>
                            <div class="icon-service"></div>
                            <div class="icon-service"></div>
                        </div>
                        <div class="btn-reservation">Reservar <i class="fa fa-long-arrow-right"></i></div>
                    </div>                   
                <% end %>
                <%end%>
                
            </div>
        </div>
    </div>
</div>

<div id="map-google">
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d35019.314846974936!2d-77.01890707182422!3d-12.191756716447857!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9105b9deeb34c327%3A0x4f7929b6bba87e8e!2sDistrito+de+Chorrillos!5e0!3m2!1ses!2spe!4v1529522159446" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aquipe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>  
    <%-# Filter -%>
    <div class="content-filter">
      <div class="close-filter">
        <div id="btn-close-filter">cerrar <i class="fa fa-close"></i></div>
      </div>
      <div class="title_principal">Filtro</div>
      <form class="filter-scroll">
        <div class="content-form-filter">
          <div class="block-form">    
            <label for="q"><i class="fa fa-tags"></i>Precio</label>
            <%= select(:object_field, "", ['Precio menor a mayor', 'Precio mayor a menor'], {}, { :class => 'select-control' }) %>
          </div>
          <div class="block-form">
            <label for="a"><i class="fa fa-cube"></i>Tipo de servicio</label>      
            <%= select(:object_field, "", ['Cochera interior','Cochera exterior'], {}, { :class => 'select-control' }) %>
          </div>
          <div class="block-form">
            <label for="c"><i class="fa fa-map-marker"></i>Ubicación</label>           
            <%= select(:object_field, "", ['Sótano', 'Techo'], {}, { :class => 'select-control' }) %>
          </div>
          <button class="btn-black btn-block" id="send" type="submit">Aceptar filtros <i class="fa fa-long-arrow-right"></i></button>
        </div>
      </form>
    </div>
    <%-# Filter -%>

    <%-# Header Navigation -%>
    <header class="wrapper-header">
      <div class="wrap-content">
        <div class="table">
          <div class="logo">
            <%= link_to root_path, :action => 'go' do %>
              <%= render 'partials/logo' %>
            <% end %>
          </div>
          <div class="session">
            <% if logged_in? %>
              <div class="btn-login" id="btn-nav-login"><i class="fa fa-user-o"></i> Bienvenido <%= current_user.first_name %> <i class="fa fa-chevron-down"></i> </div>
            <%else%>
              <div id="btn-session"> <i class="fa fa-user-o"></i> Inicia sesión <i class="fa fa-chevron-down"></i></div>
            <% end %>            
          </div>
          <div class="menu">
            <button type="button" class="menuButton collapsed">
              <span class="menuButton__name">Menu</span>
              <span class="bar_menu">
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </span>
            </button>
          </div>
        </div>
      </div>
    </header>
    
    <%-# nav -%>
    <div class="wrapper-nav">
      <div class="wrap-content">
        <nav class="content-nav">
          <%= link_to  "Inicio", root_path, class: 'link_nav' %>
          <%= link_to  "Regístrate", registro_path, class: 'link_nav' %>
          <%= link_to  "Nosotros", root_path, class: 'link_nav' %>
          
        </nav>
      </div>
    </div>

    <%-# Login -%>
    <div class="wrapper-login">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%=form_for(:session, url: login_path, :html => {:class => 'form-login'}) do |l| %>
        <div class="block-form">
          <label for="email"><i class="fa fa-user"></i> Correo</label>
          <%= l.email_field :email, class: 'select-control', placeholder: 'Ingresa tu correo' %>
        </div>
        <div class="block-form">    
          <label for="password"><i class="fa fa-lock"></i> Contraseña:</label>
          <%= l.password_field :password, class: 'select-control', placeholder: 'Ingresa tu contraseña' %>
        </div>
        <div class="block-form">    
          <a href="#" class="link-form">¿Olvidaste tu contraseña?</a>
        </div>
        <div class="block-form">
          <label><input type="checkbox" /> Recordarme</label>   
        </div>
        <%= l.submit "Iniciar Sesión", class: "btn-black btn-block", id: "send" %>
      <% end %>
      <div class="form-login-count">
        <p>¿No tienes cuenta?</p>
        <%= link_to  "Regístrate", registro_path, class: 'btn-black btn-block' %>
      </div>
    </div>

    <%-# Nav login -%>
    <div class="wrapper-nav-login">
      <div class="block-form">
        <%= link_to  "Mi cuenta", users_path %>
        <%= link_to  "Mis reservas", mis_reservaciones_path %>
        <%= link_to logout_path, method: :delete do %>
          <span class='glyphicon glyphicon-log-in'> Salir</span>
        <% end %>
      </div>
    </div>

    <%= yield %>

    

    <%-# Footer -%>
    <footer class="wrapper-footer">
      <div class="wrapper-content">
          <div class="cf">
            <div class="logo-footer">
              <%= render 'partials/logo-footer' %>
            </div>
            <div class="nav-footer">
              <%= link_to  "Inicio", root_path %>
              <%= link_to  "Nosotros", :controller => "users", :action => "index" %>
              <%= link_to  "Inicia sesión", :controller => "users", :action => "index" %>
              <%= link_to  "Regístrate", :controller => "users", :action => "index" %>
            </div>
            <div class="tyc">
              <a href="#">Ayuda</a>
              <a href="#">Términos y condiciones</a>
              <div class="social-footer">
                <a href="https://www.facebook.com/" target="_blank"><i class="fa fa-facebook"></i></a>
                <a href="https://twitter.com/?lang=es" target="_blank"><i class="fa fa-twitter"></i></a>
                <a href="https://plus.google.com/discover" target="_blank"><i class="fa fa-google-plus"></i></a>
              </div>
            </div>
          </div>
          <div class="element-foot cf">
            <div class="copy">Todos los derechos reservados © 2018</div>
            <div class="create">Grupo N° 1</div>
          </div>
      </div>
    </footer>
    <script>
      $(document).ready(function() {
        $('#btn-close-filter, #btn-filter').click(function(){
          $('.content-filter').toggleClass("filter-active");
        });
        $('.menuButton').click(function(){
          $('.wrapper-nav').toggleClass("nav-active");
        });
        $('#btn-session').click(function(){
          $('.wrapper-login').toggleClass("login-active");
        });
        $('#btn-nav-login').click(function(){
          $('.wrapper-nav-login').toggleClass("login-active");
        });
      });

    </script>
  </body>
</html>

app/views/pages/sesion.html.erb
<h1>Pages#sesion</h1>
<p>Find me in app/views/pages/sesion.html.erb</p>

app/views/users/index.html.erb
<div class="wrapper-inner wrapper-cuenta wrapper-black">
    <div class="wrapper-content">    
        <div class="title">Bienvenido</div>
        <div class="title color-amarillo"><%= current_user.first_name %> <%= current_user.last_name %></div>

        <div class="border-black info-content-count">
            <div class="sub-title">¿Tienes un estacionamiento vacio? Nosotros nos encargaremos de que se alquile</div>
            <div class="row cf">
                <div class="col-sm-8">
                    <p>Alquilando tu plaza de tu estacionamiento con <span class="color-amarillo">Aquí.pe</span> nosotros nos encargaremos de todo. Tú solo tendrás que preocuparte de en qué vas a gastar esos ingresos extras.<p>
                </div>
                <div class="col-sm-4">
                    <%= link_to new_parking_path, class: 'btn-yellow', :action => 'go' do %>
                        Regístra un estacionamiento <i class="fa fa-long-arrow-right"></i>
                    <% end %>
                </div>
            </div>
        </div>

        <div class="row cf count-option"> 
            <div class="col-xs-12 col-sm-4">
                <div class="subtitle">Configuración de tu cuenta</div>
            </div>
            <div class="col-xs-6 col-sm-4">
                <%= link_to actualizar_path, class: 'btn-count' do %>
                    Actualizar <br/> mis datos
                    <i class="fa fa-arrow-right"></i>
                <% end %>
            </div>
            <div class="col-xs-6 col-sm-4">
                <a href="#" class="btn-count">
                    Actualizar <br> Contraseña
                    <i class="fa fa-arrow-right"></i>
                </a>
            </div>
        </div>
    </div>
</div>